Update microos script to support .zst file
aplanas/meta-microos pull request #1
Opened 2024-02-04 23:18 UTC by pyy

simple way without third part python library.

2024-02-05 07:03 UTC, aplanas requested changes
Thanks a lot for this contribution

2024-02-05 07:03 UTC, aplanas commented on scripts/microos
> +        os.system(f"wget -O primary.xml.zst {url} && unzstd --rm primary.xml.zst")
I think that the correct what is not to call `wget` nor `unzstd`. The python code is already downloading the `primary.xml.zst` with `urllib.request.urlopen()`. We can add a new dependency: [zstandard](https://pypi.org/project/zstandard/) and use it to decompress it

2024-02-20 00:28 UTC, pyy commented
Hello, thanks for your suggestions. Here is the change.
Now it is using `ET.fromstring()`, is it okay? I don't know how to let zstandard return a file object like `gzip.open()`

Here is another way to consider: https://github.com/openSUSE/openSUSE-release-tools/blob/54075b05b13b59086abf167ddfa7fcca3eba78d7/repo2fileprovides.py#L17

2024-02-20 09:33 UTC, aplanas approved these changes
Both options are OK, so this one LGTM.

Thanks!!

2024-02-20 09:34 UTC, merged